substitutions:
  devicename: "b2500-attic-1"
  friendly_name: "B2500 Attic 1"
  b2500_update_interval: "10s"

packages:
  private_data: !include common/wifinordkorea.yaml
  base_config: !include common/base.yaml
  hw_base: !include common/hw_esp32_s3_devkitc.yaml
  b2500_gateway: !include common/b2500_gateway_base.yaml

  b2500_1: !include
    file: common/b2500_v2_storage.yaml
    vars:
      b2500_name: "B2500 1"
      b2500_mac: "B4:2F:03:98:B1:41"
      b2500_id: "b2500_1"
      b2500_ble_client_id: "b2500_ble_1"

  b2500_2: !include
    file: common/b2500_v2_storage.yaml
    vars:
      b2500_name: "B2500 2"
      b2500_mac: "60:32:3B:D1:32:0D"
      b2500_id: "b2500_2"
      b2500_ble_client_id: "b2500_ble_2"
